### ISSUE TITLE
32x ignores bank switching

### ISSUE THREAD

**Issue by gitymon** [notaz/picodrive#75]
SH2 access on ROM addresses ( 0200 0000h - 0240 0000h ) ignores the bank setup registers (A1 30F1h - A1 30FFh). 

reference tests i did on hardware (Everdrive) and emulator (KegaFusion) do both rewire the accesses, and allow me reading above 4MB from 32X. 

( I can supply a test ROM if the problem is unclear)

**Comment by notaz** [comment]
Yeah I haven't bothered to implement it because no 32X games ever used that mapper.

I've pushed an attempt to implement it. It will only activate if the ROM size is above 4MB; I don't want it on by default as the vast majority of carts don't have that mapper. If it doesn't work, please provide a test ROM.

**Comment by gitymon** [comment]
a test rom: [bankswitcher.zip](https://github.com/notaz/picodrive/files/1653832/bankswitcher.zip)
it randomly switches banks every 3 seconds

**Comment by notaz** [comment]
Thanks for a nice test, I think it should be good now.
